- hosts: all
  roles:
  - role: git
    tags:
    - shell
    - git
    - scm
    - vcs
  - role: zsh
    tags:
    - zsh
    - shell
  - role: vim
    tags:
    - shell
    - vim
  - role: gpg
    tags:
    - shell
    - gpg
    - gnupg
  - role: cli-tools
    tags:
    - shell
    - tools
    - cli-tools
  - role: docker
    tags:
    - docker
    - docker-compose
    - docker-machine
    - ops
    - container
  - role: terraform
    tags:
    - ops
    - tools
    - terraform
  - role: java
    tags:
    - shell
    - dev
    - java
    - jdk
  - role: golang
    tags:
    - dev
    - go
    - golang
  - role: vscode
    tags:
    - dev
    - vscode
  - role: idea
    tags:
    - dev
    - idea
  - role: trivy
    tags:
    - trivy
  - role: backup
    tags:
    - backup
    - restic
  - role: aws
    tags:
    - shell
  - role: rust
    tags:
    - shell
