- name: Install vscode (Arch)
  become: yes
  shell: git clone https://aur.archlinux.org/visual-studio-code-bin.git && cd visual-studio-code-bin && makepkg -si 
  when: ansible_distribution == "Archlinux"

- name: Install vscode (Ubuntu)
  become: yes
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu" or ansible_facts['distribution'] == 'Linux Mint'

- name: Install vscode (MacOSX)
  homebrew_cask:
    name: visual-studio-code
  when: ansible_distribution == "MacOSX"

- name: install vscode extensions
  command: "code --install-extension '{{ item }}'"
  with_items:
  - ms-azuretools.vscode-docker
  - EditorConfig.EditorConfig
  - dbaeumer.vscode-eslint
  - esbenp.prettier-vscode
  - k--kato.intellij-idea-keybindings
  - jebbs.plantuml
  - msjsdiag.debugger-for-chrome
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
