- name: Download docker_aliases
  get_url:
    url: "https://github.com/schnatterer/docker-aliases/releases/download/{{ docker_aliases_version }}/default.docker-aliases"
    dest: ~/.docker_aliases
    mode: '0440'
