- name: Install cli tools from repository (Ubuntu/Mint)
  become: yes
  apt:
    name:
    - htop
    - iftop
    - make
    - openssl
    - wget
    - curl
    - subversion
    - jq
    - ncdu
  when: ansible_distribution == "Ubuntu" or ansible_facts['distribution'] == 'Linux Mint'

- name: Install cli tools from repository (Arch)
  become: yes
  pacman:
    name:
    - htop
    - iftop
    - make
    - openssl
    - wget
    - curl
    - subversion
    - jq
    - ncdu
  when: ansible_distribution == "Archlinux"

- name: Install cli tools from repository (MacOSX)
  homebrew:
    name:
    - htop
    - iftop
    - make
    - openssl
    - wget
    - curl
    - subversion
    - jq
    - ctop
    - gopass
    - vegeta
    - ncdu
  when: ansible_distribution == "MacOSX"

- name: Install bat
  include: bat.yml

- name: Install ctop
  include: ctop.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Archlinux" or ansible_facts['distribution'] == 'Linux Mint'

- name: Install vegeta
  include: vegeta.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Archlinux" or ansible_facts['distribution'] == 'Linux Mint'

- name: Install aliases
  include: aliases.yml
