- name: Download SDKMAN installer
  get_url: 
    url: https://get.sdkman.io dest=/tmp/sdk-installer.sh
    
- name: Execute the sdk-installer.sh
  shell: /tmp/sdk-installer.sh

- name: Install java
  shell: sdk install java 17.0.4-zulu

- name: Remove the sdk-installer.sh
  file: 
    path: /tmp/sdk-installer.sh 
    state: absent

- name: Create java-env plugin directory
  file:
    path: ~/.oh-my-zsh/custom/plugins/java-env
    state: directory

- name: Link java-env plugin
  file:
    src: "{{ playbook_dir }}/config/oh-my-zsh-plugins/java-env.plugin.zsh"
    dest: ~/.oh-my-zsh/custom/plugins/java-env/java-env.plugin.zsh
    state: link
