# node and npm installed through oh my zsh
- name: Install global npm packages
  become: yes
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
  - colortest
  - prettier
  - create-react-app
  - tldr
